# Generated by Django 4.2.1 on 2023-05-11 16:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("board", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="posts",
            name="category",
            field=models.IntegerField(
                choices=[
                    (1, "Diet"),
                    (2, "Beginner"),
                    (3, "Intermediate"),
                    (4, "Advanced"),
                ]
            ),
        ),
    ]
