# Generated by Django 4.2.1 on 2023-05-21 08:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0001_initial"),
        ("board", "0002_alter_posts_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comments",
            name="user_id",
            field=models.ForeignKey(
                db_column="user_id",
                on_delete=django.db.models.deletion.CASCADE,
                to="common.userdata",
            ),
        ),
        migrations.AlterField(
            model_name="posts",
            name="user_id",
            field=models.ForeignKey(
                db_column="user_id",
                on_delete=django.db.models.deletion.CASCADE,
                to="common.userdata",
            ),
        ),
    ]
